Repository vultr/terraform-provider-vultr, pull requests merged in 2020-05, with the labels that each got.

#38 Fix typo
  website/docs/index.html.markdown
Labels: documentation, size/XS

#37 Load Balancer resource + Datasource
  example/main.tf
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-getter/.travis.yml
  vendor/github.com/hashicorp/go-getter/README.md
  vendor/github.com/hashicorp/go-getter/client.go
  vendor/github.com/hashicorp/go-getter/get_git.go
  vendor/github.com/hashicorp/go-getter/get_http.go
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
  vendor/github.com/hashicorp/hcl/v2/README.md
  vendor/github.com/hashicorp/hcl/v2/appveyor.yml
  vendor/github.com/hashicorp/hcl/v2/ext/customdecode/README.md
  vendor/github.com/hashicorp/hcl/v2/ext/customdecode/customdecode.go
  vendor/github.com/hashicorp/hcl/v2/ext/customdecode/expression_type.go
  vendor/github.com/hashicorp/hcl/v2/ext/typeexpr/README.md
  vendor/github.com/hashicorp/hcl/v2/ext/typeexpr/type_type.go
  vendor/github.com/hashicorp/hcl/v2/go.mod
  vendor/github.com/hashicorp/hcl/v2/go.sum
  vendor/github.com/hashicorp/hcl/v2/gohcl/decode.go
  vendor/github.com/hashicorp/hcl/v2/hcldec/spec.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_body.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_expression.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/generate.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/load.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/load_hcl.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/load_legacy.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/module.go
  vendor/github.com/hashicorp/terraform-config-inspect/tfconfig/provider_ref.go
  vendor/github.com/vultr/govultr/.travis.yml
  vendor/github.com/vultr/govultr/CHANGELOG.md
  vendor/github.com/vultr/govultr/go.mod
  vendor/github.com/vultr/govultr/go.sum
  vendor/github.com/vultr/govultr/govultr.go
  vendor/github.com/vultr/govultr/load_balancer.go
  vendor/github.com/vultr/govultr/object_storage.go
  vendor/modules.txt
  vultr/data_source_vultr_load_balancer.go
  vultr/data_source_vultr_load_balancer_test.go
  vultr/provider.go
  vultr/resource_vultr_load_balancer.go
  vultr/resource_vultr_load_balancer_test.go
  website/docs/d/load_balancer.html.markdown
  website/docs/r/load_balancer.html.markdown
  website/vultr.erb
Labels: dependencies, enhancement, size/XXL

#39 release for v1.2.0
  CHANGELOG.md
Labels: size/XS
