Repository vultr/terraform-provider-vultr, pull requests merged in 2021-12, with the labels that each got.

#182 Bump govultr to v2.12.0, adjust monthly charges to float
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/v2/CHANGELOG.md
  vendor/github.com/vultr/govultr/v2/govultr.go
  vendor/github.com/vultr/govultr/v2/load_balancer.go
  vendor/github.com/vultr/govultr/v2/plans.go
  vendor/modules.txt
  vultr/data_source_vultr_plan.go
Labels: dependencies

#185 Added autoreleaser
  .github/workflows/release.yml
Labels: enhancement

#186 Release v2.7.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#187 Fix MM notification
  .github/workflows/release.yml
Labels: bug

#188 Implement data source filtering on string lists.
  vultr/data_source_vultr_common_schema.go
Labels: enhancement

#189 Release v2.8.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#193 Release v2.8.1 #patch
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#195 Adding dependabot
  .github/dependabot.yml
Labels: dependencies
