Repository vultr/terraform-provider-vultr, pull requests merged in 2022-03, with the labels that each got.

#216 Docs : adjust types in instances + vke discalimer
  website/docs/r/instance.html.markdown
  website/docs/r/kubernetes.html.markdown
Labels: documentation

#220 Updated domain for rdns test
  vultr/data_source_vultr_reverse_ipv4_test.go
Labels: enhancement

#221 Bumped Go to v1.17
  .github/workflows/release.yml
  .goreleaser.yml
  go.mod
  vendor/github.com/agext/levenshtein/go.mod
  vendor/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/hashicorp/go-checkpoint/go.mod
  vendor/github.com/hashicorp/go-checkpoint/go.sum
  vendor/github.com/hashicorp/go-cleanhttp/go.mod
  vendor/github.com/hashicorp/go-hclog/go.mod
  vendor/github.com/hashicorp/go-hclog/go.sum
  vendor/github.com/hashicorp/go-multierror/go.mod
  vendor/github.com/hashicorp/go-multierror/go.sum
  vendor/github.com/hashicorp/go-plugin/go.mod
  vendor/github.com/hashicorp/go-plugin/go.sum
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/hashicorp/go-uuid/go.mod
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/hc-install/go.mod
  vendor/github.com/hashicorp/hc-install/go.sum
  vendor/github.com/hashicorp/hcl/v2/go.mod
  vendor/github.com/hashicorp/hcl/v2/go.sum
  vendor/github.com/hashicorp/logutils/go.mod
  vendor/github.com/hashicorp/terraform-json/go.mod
  vendor/github.com/hashicorp/terraform-json/go.sum
  vendor/github.com/hashicorp/terraform-registry-address/go.mod
  vendor/github.com/hashicorp/terraform-registry-address/go.sum
  vendor/github.com/hashicorp/terraform-svchost/go.mod
  vendor/github.com/hashicorp/terraform-svchost/go.sum
  vendor/github.com/hashicorp/yamux/go.mod
  vendor/github.com/mattn/go-colorable/go.mod
  vendor/github.com/mattn/go-colorable/go.sum
  vendor/github.com/mattn/go-isatty/go.mod
  vendor/github.com/mattn/go-isatty/go.sum
  vendor/github.com/mitchellh/copystructure/go.mod
  vendor/github.com/mitchellh/copystructure/go.sum
  vendor/github.com/mitchellh/go-testing-interface/go.mod
  vendor/github.com/mitchellh/go-wordwrap/go.mod
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/reflectwalk/go.mod
  vendor/github.com/vmihailenco/msgpack/v4/go.mod
  vendor/github.com/vmihailenco/msgpack/v4/go.sum
  vendor/github.com/vmihailenco/tagparser/go.mod
  vendor/github.com/vultr/govultr/v2/go.mod
  vendor/github.com/vultr/govultr/v2/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/modules.txt
Labels: enhancement

#222 vultr_resource_block : add waits for active
  vultr/resource_vultr_block_storage.go
Labels: enhancement

#225 Warn that updating hostname triggers reinstall
  vultr/resource_vultr_instance.go
  website/docs/r/instance.html.markdown
Labels: documentation, enhancement

#228 Release v2.10.1 #patch
  .goreleaser.yml
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release
