Repository vultr/terraform-provider-vultr, pull requests merged in 2022-05, with the labels that each got.

#240 Add support for tags to instances and bare metal servers
  vultr/data_source_vultr_bare_metal_server.go
  vultr/data_source_vultr_instance.go
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_bare_metal_server_test.go
  vultr/resource_vultr_instance.go
  vultr/resource_vultr_instance_test.go
  vultr/utility.go
  website/docs/d/bare_metal_server.html.markdown
  website/docs/d/instance.html.markdown
  website/docs/r/bare_metal_server.html.markdown
  website/docs/r/instance.html.markdown
Labels: enhancement

#244 Add link to quickstart guide
  README.md
Labels: documentation

#246 Update example and docs to apply without error.
  example/main.tf
  website/docs/r/instance.html.markdown
Labels: documentation

#247 Add support for VKE auto scaler options
  vultr/data_source_vultr_kubernetes.go
  vultr/resource_vultr_kubernetes.go
  vultr/resource_vultr_kubernetes_nodepools.go
  vultr/resource_vultr_kubernetes_nodepools_test.go
  vultr/resource_vultr_kubernetes_test.go
  vultr/vke.go
  website/docs/d/kubernetes.html.markdown
  website/docs/r/kubernetes.html.markdown
  website/docs/r/kubernetes_node_pools.html.markdown
Labels: enhancement

#248 allow removal of default node pool
  vultr/resource_vultr_kubernetes.go
Labels: enhancement

#250 Release v2.11.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#251 Fix incorrect import example
  website/docs/r/instance.html.markdown
Labels: documentation

#258 Release v2.11.1 #patch
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release
