Repository vultr/terraform-provider-vultr, pull requests merged in 2022-01, with the labels that each got.

#198 VKE Datasource
  vultr/data_source_vultr_kubernetes.go
  vultr/data_source_vultr_kubernetes_test.go
  vultr/provider.go
  website/docs/d/kubernetes.html.markdown
  website/vultr.erb
Labels: enhancement, new-data-source

#199 Fixed nightly acceptance notification
  .github/workflows/nightly-acceptance.yml
Labels: bug

#201 Datasource Backups : fix schema mismatch
  .github/workflows/nightly-acceptance.yml
  vultr/data_source_vultr_backup.go
Labels: bug

#202 Updated nightly acceptance workflow
  .github/workflows/nightly-acceptance.yml
  scripts/clean.sh
Labels: enhancement

#203 Moved tests to AMS
  vultr/data_source_vultr_bare_metal_server_test.go
  vultr/resource_vultr_bare_metal_server_test.go
Labels: enhancement

#207 Release v2.9.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release
