Repository vultr/terraform-provider-vultr, pull requests merged in 2023-09, with the labels that each got.

#389 Add VPC 2.0
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/v3/CHANGELOG.md
  vendor/github.com/vultr/govultr/v3/bare_metal_server.go
  vendor/github.com/vultr/govultr/v3/govultr.go
  vendor/github.com/vultr/govultr/v3/instance.go
  vendor/github.com/vultr/govultr/v3/network.go
  vendor/github.com/vultr/govultr/v3/vpc.go
  vendor/github.com/vultr/govultr/v3/vpc2.go
  vendor/modules.txt
  vultr/data_source_vultr_bare_metal_server.go
  vultr/data_source_vultr_instance.go
  vultr/data_source_vultr_vpc2.go
  vultr/data_source_vultr_vpc2_test.go
  vultr/instances.go
  vultr/provider.go
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_bare_metal_server_test.go
  vultr/resource_vultr_instance.go
  vultr/resource_vultr_instance_test.go
  vultr/resource_vultr_vpc2.go
  vultr/resource_vultr_vpc2_test.go
  website/docs/d/bare_metal_server.html.markdown
  website/docs/d/instance.html.markdown
  website/docs/d/vpc2.html.markdown
  website/docs/r/bare_metal_server.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/vpc2.html.markdown
  website/vultr.erb
Labels: enhancement, dependencies

#399 Fix delete retries and detach errors with VPC2s
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_instance.go
  vultr/resource_vultr_vpc2.go
Labels: bug, regression

#400 Revert BM update delay for detach VPC2
  go.mod
  go.sum
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
  vultr/resource_vultr_bare_metal_server.go
Labels: enhancement

#401 Release-v2.16.1 #patch
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#402 Release v2.16.1 #patch
  CHANGELOG.md
Labels: release

#403 Add missing vpc_id property to managed database read replicas
  vultr/database.go
Labels: bug

#384 Add a per-page param for instance data source
  vultr/data_source_vultr_instance.go
Labels: enhancement

#405 Extend the nightly acceptance test timeout by one hour
  .github/workflows/nightly-acceptance.yml
Labels: automation
