Repository vultr/terraform-provider-vultr, pull requests merged in 2023-05, with the labels that each got.

#354 Release v2.15.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#356 Add documentation for Vultr managed database data sources and resources
  website/docs/d/database.html.markdown
  website/docs/r/database.html.markdown
  website/docs/r/database_connection_pool.html.markdown
  website/docs/r/database_db.html.markdown
  website/docs/r/database_replica.html.markdown
  website/docs/r/database_user.html.markdown
Labels: documentation

#358 Add delete retries
  vultr/resource_vultr_load_balancer.go
  vultr/resource_vultr_vpc.go
Labels: enhancement

#359 Release v2.15.1 #patch
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#361 Update goreleaser-action to v4 and fix `release` args
  .github/workflows/release.yml
Labels: automation

#362 Add/update instance and VPC retry on create/delete actions
  vultr/resource_vultr_instance.go
  vultr/resource_vultr_vpc.go
Labels: enhancement
