Repository vultr/terraform-provider-vultr, pull requests merged in 2023-10, with the labels that each got.

#409 Update a few of the resource documentation pages
  website/docs/r/bare_metal_server.html.markdown
  website/docs/r/block_storage.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/kubernetes.html.markdown
  website/docs/r/load_balancer.html.markdown
  website/docs/r/object_storage.html.markdown
Labels: documentation

#411 Release v2.16.3 #patch
  CHANGELOG.md
Labels: release

#412 Fix docs typo on VKE node plan
  website/docs/r/kubernetes.html.markdown
Labels: documentation

#413 Release v2.16.4 #patch
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#414 Update some invalid plans in documentation
  example/variable.tf
  vultr/data_source_vultr_instance_ipv4_test.go
  vultr/data_source_vultr_instance_test.go
  vultr/data_source_vultr_plan_test.go
  vultr/data_source_vultr_reverse_ipv4_test.go
  vultr/data_source_vultr_reverse_ipv6_test.go
  vultr/data_source_vultr_snapshot_test.go
  vultr/resource_vultr_block_storage_test.go
  vultr/resource_vultr_instance_ipv4_test.go
  vultr/resource_vultr_instance_test.go
  vultr/resource_vultr_reserved_ip_test.go
  vultr/resource_vultr_reverse_ipv4_test.go
  vultr/resource_vultr_reverse_ipv6_test.go
  vultr/resource_vultr_snapshot_test.go
  website/docs/d/plan.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/load_balancer.html.markdown
  website/docs/r/reverse_ipv4.html.markdown
Labels: documentation

#415 Update govultr to v3.3.2
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/v3/CHANGELOG.md
  vendor/github.com/vultr/govultr/v3/README.md
  vendor/github.com/vultr/govultr/v3/database.go
  vendor/github.com/vultr/govultr/v3/govultr.go
  vendor/modules.txt
Labels: dependencies

#417 Update govultr to v3.3.3
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/v3/CHANGELOG.md
  vendor/github.com/vultr/govultr/v3/database.go
  vendor/github.com/vultr/govultr/v3/govultr.go
  vendor/modules.txt
  vultr/resource_vultr_database.go
Labels: dependencies

#416 Add support for public/private DBaaS hostnames
  vultr/data_source_vultr_database.go
  vultr/resource_vultr_database.go
  website/docs/d/database.html.markdown
  website/docs/r/database.html.markdown
Labels: enhancement

#418 Release v2.17.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#421 Update govultr to v3.3.4
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/v3/CHANGELOG.md
  vendor/github.com/vultr/govultr/v3/database.go
  vendor/github.com/vultr/govultr/v3/govultr.go
  vendor/github.com/vultr/govultr/v3/kubernetes.go
  vendor/modules.txt
Labels: dependencies

#422 Managed Databases FerretDB Support
  vultr/data_source_vultr_database.go
  vultr/database.go
  vultr/resource_vultr_database.go
  vultr/resource_vultr_database_replica.go
  website/docs/d/database.html.markdown
  website/docs/r/database.html.markdown
  website/docs/r/database_replica.html.markdown
Labels: enhancement

#423 Add support for the VKE HA control plane option
  vultr/data_source_vultr_kubernetes.go
  vultr/resource_vultr_kubernetes.go
  website/docs/d/kubernetes.html.markdown
  website/docs/r/kubernetes.html.markdown
Labels: enhancement

#424 Add Computed to ForceNew, Optional VPC2 fields
  vultr/resource_vultr_vpc2.go
Labels: bug

#425 Release v2.17.1 #patch
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release
