Repository vultr/terraform-provider-vultr, pull requests merged in 2023-12, with the labels that each got.

#438 Update govultr from v3.4.0 to v3.5.0
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/v3/CHANGELOG.md
  vendor/github.com/vultr/govultr/v3/bare_metal_server.go
  vendor/github.com/vultr/govultr/v3/container_registry.go
  vendor/github.com/vultr/govultr/v3/database.go
  vendor/github.com/vultr/govultr/v3/govultr.go
  vendor/github.com/vultr/govultr/v3/instance.go
  vendor/modules.txt
  vultr/resource_vultr_bare_metal_server.go
Labels: dependencies

#439 Support Managed Redis User Access Control
  vultr/database.go
  vultr/resource_vultr_database.go
  vultr/resource_vultr_database_connection_pool_test.go
  vultr/resource_vultr_database_db_test.go
  vultr/resource_vultr_database_replica_test.go
  vultr/resource_vultr_database_test.go
  vultr/resource_vultr_database_user.go
  vultr/resource_vultr_database_user_test.go
  website/docs/r/database_user.html.markdown
Labels: enhancement

#441 Release v2.18.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#444 Update govultr from v3.5.0 to v3.6.0
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/v3/CHANGELOG.md
  vendor/github.com/vultr/govultr/v3/README.md
  vendor/github.com/vultr/govultr/v3/bare_metal_server.go
  vendor/github.com/vultr/govultr/v3/govultr.go
  vendor/github.com/vultr/govultr/v3/instance.go
  vendor/github.com/vultr/govultr/v3/marketplace.go
  vendor/modules.txt
Labels: dependencies
