Repository vultr/terraform-provider-vultr, pull requests merged in 2023-11, with the labels that each got.

#427 Fix bug with flattening non-FerretDB DBaaS replicas
  vultr/data_source_vultr_database.go
Labels: bug

#368 Bare Metal Persistent PXE
  vendor/github.com/vultr/govultr/v3/bare_metal_server.go
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_bare_metal_server_test.go
Labels: enhancement

#296 Add instances data source
  vultr/data_source_vultr_instances.go
  vultr/data_source_vultr_instances_test.go
  vultr/provider.go
Labels: enhancement

#431 Add web docs for the instances data source
  website/docs/d/instances.html.markdown
Labels: documentation

#432 Remove deprecated SDK meta version function usage
  vultr/config.go
Labels: dependencies, automation
