Repository vultr/terraform-provider-vultr, pull requests merged in 2024-11, with the labels that each got.

#522 Support Managed Kafka
  vultr/data_source_vultr_database.go
  vultr/database.go
  vultr/provider.go
  vultr/resource_vultr_database.go
  vultr/resource_vultr_database_quota.go
  vultr/resource_vultr_database_quota_test.go
  vultr/resource_vultr_database_test.go
  vultr/resource_vultr_database_topic.go
  vultr/resource_vultr_database_topic_test.go
  vultr/resource_vultr_database_user.go
  vultr/resource_vultr_database_user_test.go
  website/docs/d/database.html.markdown
  website/docs/r/database.html.markdown
  website/docs/r/database_quota.html.markdown
  website/docs/r/database_topic.html.markdown
  website/docs/r/database_user.html.markdown
Labels: enhancement

#523 Release v2.22.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#525 Set default value for user_scheme
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_instance.go
Labels: bug, regression

#526 Release v2.22.1 #patch
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release

#531 Remove the kubernetes set on enable_firewall
  vultr/resource_vultr_kubernetes.go
Labels: bug

#532 Update govultr from v3.11.2 to v3.12.0
  go.mod
  go.sum
Labels: dependencies

#533 Deprecate Redis-Named Fields
  vultr/data_source_vultr_database.go
  vultr/database.go
  vultr/resource_vultr_database.go
  vultr/resource_vultr_database_replica.go
  vultr/resource_vultr_database_user.go
  website/docs/d/database.html.markdown
  website/docs/r/database.html.markdown
  website/docs/r/database_replica.html.markdown
  website/docs/r/database_user.html.markdown
Labels: breaking-change, clean-up

#528 Fix default tag checking for vultr_kubernetes resource
  vultr/resource_vultr_kubernetes.go
Labels: bug

#535 Add provider installation instructions to README
  README.md
Labels: documentation
