Repository vultr/terraform-provider-vultr, pull requests merged in 2024-06, with the labels that each got.

#445 feat: add vultr container registry resource
  example/V2Changes.md
  example/main.tf
  example/outputs.tf
  vultr/provider.go
  vultr/resource_vultr_container_registry.go
  vultr/resource_vultr_container_registry_test.go
Labels: enhancement

#493 Update containter registry to add validation and a data source resource
  vultr/data_source_vultr_container_registry.go
  vultr/provider.go
  vultr/resource_vultr_container_registry.go
  vultr/resource_vultr_container_registry_test.go
  website/docs/d/container_registry.html.markdown
  website/docs/r/container_registry.html.markdown
Labels: enhancement

#496 Remove all private_network resources
  vultr/data_source_vultr_private_network.go
  vultr/provider.go
  vultr/resource_vultr_private_network.go
  website/docs/d/private_network.html.markdown
  website/docs/r/private_network.html.markdown
Labels: technical-debt

#495 Change `vultr_user.acl` to typeset as the ordering is not important and causes extraneous plans
  vultr/resource_vultr_users.go
Labels: bug

#498 Lint fixes; add an updated lint configuration
  .golangci.yaml
  vultr/data_source_vultr_account.go
  vultr/data_source_vultr_application.go
  vultr/data_source_vultr_bare_metal_server.go
  vultr/data_source_vultr_container_registry.go
  vultr/data_source_vultr_firewall_group.go
  vultr/data_source_vultr_firewall_group_test.go
  vultr/data_source_vultr_instance.go
  vultr/data_source_vultr_instance_ipv4.go
  vultr/data_source_vultr_kubernetes.go
  vultr/data_source_vultr_load_balancer.go
  vultr/data_source_vultr_object_storage_cluster.go
  vultr/data_source_vultr_reverse_ipv4.go
  vultr/data_source_vultr_reverse_ipv6.go
  vultr/data_source_vultr_snapshot.go
  vultr/data_source_vultr_ssh_key.go
  vultr/data_source_vultr_ssh_key_test.go
  vultr/data_source_vultr_startup_script.go
  vultr/data_source_vultr_startup_script_test.go
  vultr/data_source_vultr_user.go
  vultr/data_source_vultr_user_test.go
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_block_storage.go
  vultr/resource_vultr_block_storage_test.go
  vultr/resource_vultr_container_registry.go
  vultr/resource_vultr_database.go
  vultr/resource_vultr_database_connection_pool.go
  vultr/resource_vultr_database_db.go
  vultr/resource_vultr_database_replica.go
  vultr/resource_vultr_database_user.go
  vultr/resource_vultr_dns_domain.go
  vultr/resource_vultr_dns_domain_test.go
  vultr/resource_vultr_dns_records.go
  vultr/resource_vultr_dns_records_test.go
  vultr/resource_vultr_firewall_group_test.go
  vultr/resource_vultr_firewall_rule.go
  vultr/resource_vultr_firewall_rule_test.go
  vultr/resource_vultr_instance.go
  vultr/resource_vultr_iso_private.go
  vultr/resource_vultr_iso_private_test.go
  vultr/resource_vultr_kubernetes.go
  vultr/resource_vultr_kubernetes_nodepools.go
  vultr/resource_vultr_load_balancer.go
  vultr/resource_vultr_object_storage.go
  vultr/resource_vultr_reverse_ipv4.go
  vultr/resource_vultr_reverse_ipv6.go
  vultr/resource_vultr_snapshot.go
  vultr/resource_vultr_snapshot_from_url.go
  vultr/resource_vultr_snapshot_test.go
  vultr/resource_vultr_ssh_key_test.go
  vultr/resource_vultr_users_test.go
  vultr/utility.go
  vultr/vke.go
Labels: enhancement, automation

#500 Update govultr from v2.7.0 to v2.8.1
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/vultr/govultr/v3/.golangci.yaml
  vendor/github.com/vultr/govultr/v3/CHANGELOG.md
  vendor/github.com/vultr/govultr/v3/database.go
  vendor/github.com/vultr/govultr/v3/govultr.go
  vendor/modules.txt
Labels: dependencies

#501 Support Vultr Serverless Inference
  vendor/github.com/vultr/govultr/v3/inference.go
  vultr/data_source_vultr_inference.go
  vultr/provider.go
  vultr/resource_vultr_inference.go
  vultr/resource_vultr_inference_test.go
  website/docs/d/inference.html.markdown
  website/docs/r/inference.html.markdown
Labels: enhancement

#502 Release v2.21.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release
