Repository vultr/terraform-provider-vultr, pull requests merged in 2024-01, with the labels that each got.

#448 Support Marketplace App Variables
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_instance.go
  website/docs/r/bare_metal_server.html.markdown
  website/docs/r/instance.html.markdown
Labels: enhancement

#449 ci: Use GITHUB_OUTPUT envvar instead of set-output command
  .github/workflows/release.yml
Labels: automation

#452 Fix nil interface on bare metal create
  vultr/resource_vultr_bare_metal_server.go
Labels: bug

#453 Add disable_public_ipv4 to instance webdocs
  website/docs/r/instance.html.markdown
Labels: documentation

#454 Release v2.19.0 #minor
  CHANGELOG.md
  example/main.tf
  website/docs/index.html.markdown
Labels: release
