Repository vultr/terraform-provider-vultr, pull requests merged in 2024-05, with the labels that each got.

#489 add support for mdisk_mode to the vultr_bare_metal_server resource
  vultr/resource_vultr_bare_metal_server.go
  vultr/resource_vultr_bare_metal_server_test.go
Labels: enhancement

#490 Release v2.20.0 #minor
  CHANGELOG.md
  website/docs/index.html.markdown
Labels: release

#491 Update gpg key import github action
  .github/workflows/release.yml
Labels: automation
